// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6MsaFR2_HMpK3vwWRygnRJOXQFfiaCls',
    appId: '1:174701045341:web:63edb0cc23c1f5d32acfb4',
    messagingSenderId: '174701045341',
    projectId: 'attendacetracker-98c35',
    authDomain: 'attendacetracker-98c35.firebaseapp.com',
    storageBucket: 'attendacetracker-98c35.appspot.com',
    measurementId: 'G-SXBZ6DHKNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI9yjteK5_dHBDP3erji40h9NdAEYo6aE',
    appId: '1:174701045341:android:a6ea904d77d479c22acfb4',
    messagingSenderId: '174701045341',
    projectId: 'attendacetracker-98c35',
    storageBucket: 'attendacetracker-98c35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbzFe32Qi_OSTGAEvyfB5PTVArdbZG4Ww',
    appId: '1:174701045341:ios:86b47446ad5484c72acfb4',
    messagingSenderId: '174701045341',
    projectId: 'attendacetracker-98c35',
    storageBucket: 'attendacetracker-98c35.appspot.com',
    iosClientId: '174701045341-6ilat49469s4p8rs31vka22sv9tmbgk6.apps.googleusercontent.com',
    iosBundleId: 'com.flutterblaster.upasthit.upasthit',
  );
}
